{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dictionar6
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dictionar6_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dictionar6/dictionar6_{{ version }}.tar.gz
  sha256: 2e55026e43adf8dc6929bd9c09a5e67bc57d148560a0d1e2840f5fe22f2ae9e5

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-ooplah
  run:
    - r-base
    - r-r6
    - r-ooplah

test:
  commands:
    - $R -e "library('dictionar6')"           # [not win]
    - "\"%R%\" -e \"library('dictionar6')\""  # [win]

about:
  home: https://xoopR.github.io/dictionar6/, https://github.com/xoopR/dictionar6/
  license: MIT
  summary: Efficient object-oriented R6 dictionary capable of holding objects of any class, including R6. Typed and untyped dictionaries are provided as well as the 'usual' dictionary methods that are available in other OOP languages, for example listing keys, items, values, and methods to get/set these.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
